# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Everything is learning
email: write@s4b7r.de
# description: >- # this means to ignore newlines until "baseurl:"
#         A collection of thoughts
#description: less random, yet intersting stuff
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.s4b7r.de" # the base hostname & protocol for your site, e.g. http://example.com

goat_counter: "s4b7rgithubio" # put your GoatCounter name if you want to use GoatCounter analytics

# Social Media user names
#twitter_username:
github_username:  s4b7r
rss: rss

repository: s4b7r/s4b7r.github.io
author: Simon Bekemeier
author_github: s4b7r
author_orcid: 0000-0001-8736-8796
author_researchgate: Simon-Bekemeier
author_linkedin: simon-bekemeier-05399118a
author_twitter: s4b7r

# Build settings
markdown: kramdown
#theme: jekyll-theme-minimal
# theme: minima
# theme: no-style-please
remote_theme: s4b7r/no-style-please@s4b7rgithubio
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

minima:
        date_format: "%Y %b %d"

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page
  show_index_content_in_top: false # show content of index.md above menu

sass:
  style: :compressed
